AgencyApp/Areas/Admin/Controllers/PortfolioController.cs
using Business.Exceptions;
using Business.Services.Abstracts;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using FileNotFoundException = Business.Exceptions.FileNotFoundException;

namespace AgencyApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class PortfolioController : Controller
    {
        private readonly IPortfolioServices _portfolioServices;

        public PortfolioController(IPortfolioServices portfolioServices)
        {
            _portfolioServices = portfolioServices;
        }

        public IActionResult Index()
        {
            var listPortfolio=_portfolioServices.GetAllPortfolio();
            return View(listPortfolio);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Portfolio portfolio)
        {
            if(!ModelState.IsValid)
            {
                return View(portfolio);
            }
            if(portfolio == null)
            {
                return NotFound();
            }
            try
            {
                _portfolioServices.AddPortfolio(portfolio);
            }
            catch (EntityNullException ex)
            {

                ModelState.AddModelError("", ex.Message);
                return View();
            }
            catch (FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            catch(ContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction("Index");

        }
        public IActionResult Delete(int id)
        {
            var portfolio=_portfolioServices.GetPortfolio(x=>x.Id == id);
            if(portfolio == null)
            {
                return NotFound();
            }

            try
            {
                _portfolioServices.DeletePortfolio(portfolio.Id);
            }
            catch (EntityNullException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return NotFound(ex.Message);

            }
            catch (FileNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return NotFound(ex.Message);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("",ex.Message);
                return NotFound(ex.Message);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var portfolio = _portfolioServices.GetPortfolio(x=>x.Id == id);
            if(portfolio == null)
            {
                return NotFound();
            }
            return View(portfolio);
        }
        [HttpPost]
        public IActionResult Update(Portfolio portfolio)
        {
            if (!ModelState.IsValid)
            {
                return View(portfolio);
            }
            if (portfolio == null)
            {
                return NotFound();
            }


            try
            {
                _portfolioServices.UpdatePortfolio(portfolio.Id,portfolio);
            }
            catch (EntityNullException ex)
            {

                ModelState.AddModelError("", ex.Message);
                return View();
            }
            catch(FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            catch(ContentTypeException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(FileNotFoundException ex)
            {
                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return BadRequest();
            }
            return RedirectToAction("Index");
        }
    }
}

AgencyApp/Areas/Admin/Views/Portfolio/Create.cshtml
@using Core.Models;

@model Portfolio

<div class="container">
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="Name" style="color:red"></span>
                
            </div>
            <div class="mb-3">
                <label asp-for="Description" class="form-label">Description</label>
                <input asp-for="Description" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="Description" style="color:red"></span>

            </div>
            <div class="mb-3">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="PhotoFile" style="color:red"></span>

            </div>
           
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

AgencyApp/Areas/Admin/Views/Portfolio/Index.cshtml
@using Core.Models;


@model List<Portfolio>
@{
    int count = 1;
}
<div class="container">
    <div class="row">
        <h1>
            Portfolio
        </h1>

        <a class="btn btn-info" asp-action="Create" asp-controller="Portfolio" >Create</a>

    </div>
</div>
<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <th scope="row">@count</th>
                        <td>@item.Name</td>
                        <td>@item.Description</td>
                        <td>
                            <img src="~/Uploads/Portfolio/@item.ImgUrl" width="100" height="100" class="img-fluid"></img>
                        </td>
                        <td>
                            <a class="btn btn-warning" asp-action="Update" asp-controller="Portfolio" asp-route-id="@item.Id">Update</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-controller="Portfolio" asp-route-id="@item.Id">Delete</a>

                        </td>
                    </tr>
                    count++;
                }

            </tbody>
        </table>
    </div>
</div>

AgencyApp/Areas/Admin/Views/Portfolio/Update.cshtml
@using Core.Models;

@model Portfolio

<div class="container">
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label asp-for="Name" class="form-label">Name</label>
                <input asp-for="Name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="Name" style="color:red"></span>

            </div>
            <div class="mb-3">
                <label asp-for="Description" class="form-label">Description</label>
                <input asp-for="Description" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="Description" style="color:red"></span>

            </div>
            <div class="mb-3">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <span asp-validation-for="PhotoFile" style="color:red"></span>

            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>